name: ci

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
      - dev

env:
  LATEST_TAG: denisakp/library-manager:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      -
        name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest
         if [ –f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
      -
        name: Check Black formatting
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
      -
        name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      -
        name: Run pytest
        run: pytest

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push latest version
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.LATEST_TAG }}
